### ISSUE TITLE
geographic grouping of taxa

### ISSUE THREAD

**Issue by jhpoelen** [PietrH/tdwg2021-estimating_collection_completeness#1]
Hey @PietrH  -

thanks for sharing your analysis code for your TDWG poster. 

Can you help me understand how you did the geographic grouping?

From 

https://github.com/PietrH/tdwg2021-estimating_collection_completeness/blob/ceb6b785778bc0ad2eadce80e749dfc283a2bd6e/src/rarefaction/tdwg_poster_figures_rarefaction.Rmd#L51

I noticed that you are using the country codes to group by location. Is that how you segmented the taxa by country?

**Comment by PietrH** [comment]
Exactly, GBIF already does geocoding based on coordinate data. I experimented with my own implementation but couldn't easily improve on what GBIF was providing me with already

**Comment by jhpoelen** [comment]
@PietrH thanks for taking the time to answer my question. 

Would be neat to see an independent and comprehensive data publication on associations with country codes and taxa, and from what I can tell, you methods would help make it easier to keep an up-to-date version of the his with most recent copies of available evidence. Or do you think this is a task that that taxonomic resources should take on?
